name: Deploy Databricks

on:
  push:
    branches:
      - develop
    paths:
      - "resources/**"
      - "src/**"
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          make install-dependencies

      - name: Run unit tests
        run: |
          make unit-test

      - uses: databricks/setup-cli@main

      - name: Validate Databricks bundle
        run: |
          make validate-bundle

      - name: Deploy Databricks bundle
        run: |
          make deploy-bundle

      - name: Run Databricks job
        run: |
          make run DATABRICKS_CLUSTER_ID=${{ secrets.DATABRICKS_CLUSTER_ID }}

